### ISSUE TITLE
TestPypi failed when deploying a new peptdeep version

### ISSUE THREAD

**Issue by jalew188** [MannLabs/alphashared#5]
TestPypi failed due to pip install current version (of peptdeep) from Pypi, which is not deployed yet. Installing from TestPypi would solve this issue

https://github.com/MannLabs/alphapeptdeep/actions/runs/10841215744/job/30084883232

**Comment by jalew188** [comment]
Note that now TestPypi is poluted by cur version (v1.3.0), preventing us to deploy v1.3.0 on TestPypi

**Comment by mschwoer** [comment]
after uploading to test-pypi, it does also try to install from testpypi
![image](https://github.com/user-attachments/assets/448f165d-027e-4f8c-967b-140317a50736)

I tried the `pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple "peptdeep==1.3.0"` command and it works now, so probabvly a race condition?

I added a fix here, https://github.com/MannLabs/alphashared/pull/4/commits/a4d4cb1383257e4730063c2ba0f4becaf681383c
currently re-running it

**Comment by mschwoer** [comment]
worked
